Repository prgrms-web-devcourse-final-project/WEB3_4_HelloWorld_BE, pull requests merged in 2025-04, with the labels that each got.

#47 refactor(common) : log.info -> log.debug
  src/main/java/org/helloworld/gymmate/domain/user/trainer/business/service/BusinessValidateService.java
  src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
  src/main/java/org/helloworld/gymmate/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/org/helloworld/gymmate/security/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/org/helloworld/gymmate/security/token/JwtManager.java
Labels: minor-refactor

#53 config(common): Refactoring Application Config
  src/main/java/org/helloworld/gymmate/infra/service/KakaoMapWebClientService.java
  src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
  src/main/java/org/helloworld/gymmate/security/policy/ExpirationPolicy.java
  src/main/resources/docs/application.md
Labels: hotfix, common-feature

#56 fix(security): ExpirationPolicy Static Error
  src/main/java/org/helloworld/gymmate/security/filter/CustomAuthenticationFilter.java
  src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
  src/main/java/org/helloworld/gymmate/security/policy/ExpirationPolicy.java
  src/main/java/org/helloworld/gymmate/security/token/JwtManager.java
Labels: hotfix

#55 Refactor(myself): Implement ModifyBigthree & Bigthree Refactoring
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/dto/BigthreeCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/dto/BigthreeRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/mapper/BigthreeMapper.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
Labels: domain-refactor

#57 reafactor(gym) : 공간좌표계 도입
  build.gradle
  src/main/java/org/helloworld/gymmate/common/config/AsyncConfig.java
  src/main/java/org/helloworld/gymmate/common/initializer/SpatialIndexInitializer.java
  src/main/java/org/helloworld/gymmate/common/initializer/SpatialIndexService.java
  src/main/java/org/helloworld/gymmate/common/util/GeometryUtil.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/dto/GymCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/dto/GymUpdateRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/GymImage.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
  src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
  src/main/java/org/helloworld/gymmate/infra/service/KakaoMapWebClientService.java
  src/main/resources/application-prod.yml
Labels: domain-refactor

#60 refactor(pt) : AuthenticationPrincipal 등록
  src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClasstimeController.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClasstimeService.java
Labels: minor-refactor

#62 fix(pt) : Security Config fix
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
Labels: bugfix

#63 refactor(pt) : ptProduct TODO 완료
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
Labels: minor-refactor

#66 feat(pt) : 거리기반 PT검색
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/common/initializer/SpatialIndexService.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/ProductSearchRequest.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/SortOption.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/model/Trainer.java
Labels: new-feature, db-update

#71 feat(member):member정보 수정 로직
  src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
  src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
  src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
Labels: new-feature

#67 fix(myself): Rename Record -> Diary & Fix BigthreeService Error
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/controller/DiaryController.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/dto/DiaryCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/dto/DiaryRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/dto/DiaryResponse.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/entity/Diary.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/mapper/DiaryMapper.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/repository/DiaryRepository.java
  src/main/java/org/helloworld/gymmate/domain/myself/diary/service/DiaryService.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/controller/RecordController.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordResponse.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/entity/Record.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/mapper/RecordMapper.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/service/RecordService.java
Labels: bugfix, domain-refactor, db-update

#69 feat(gym) : 편의 시설 등록 구현
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/facility/dto/FacilityRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/facility/entity/Facility.java
  src/main/java/org/helloworld/gymmate/domain/gym/facility/mapper/FacilityMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/facility/repository/FacilityRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/GymInfoRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
  src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
Labels: new-feature

#74 refactor(gym) : 제휴 헬스장 등록 리팩토링
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/GymProductRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/GymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/RegisterGymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/PartnerGym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
Labels: minor-refactor

#73 feat(gym) : 운동기구 등록
  src/main/java/org/helloworld/gymmate/common/validate/custom/AbstractImageFileValidator.java
  src/main/java/org/helloworld/gymmate/common/validate/custom/ImageFileValidator.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/entity/Machine.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/repository/MachineRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
Labels: new-feature, resolve-merge-conflict

#76 feat(gym) : GymService 편의시설 업데이트 추가
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
Labels: new-feature

#75 feat(trainer) : 트레이너 전체 조회 & 검색
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/ProductSearchRequest.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/PtProductSearchOption.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/PtProductSortOption.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/repository/AwardRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerListResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/enums/TrainerSearchOption.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/enums/TrainerSortOption.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
Labels: new-feature

#81 feat(machine) : 등록된 머신 삭제
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
Labels: new-feature

#79 feat(gym) : 편의 시설 조회 구현
  src/main/java/org/helloworld/gymmate/domain/gym/facility/dto/FacilityResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/facility/mapper/FacilityMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
Labels: new-feature

#83 feat(machine) : 기구목록 조회
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/FacilityAndMachineResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/repository/MachineRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
Labels: new-feature

#78 feat(gymProduct): 헬스장 이용권 등록 구현
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/RegisterGymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/PartnerGym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/dto/GymProductRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/entity/GymProduct.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/mapper/GymProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/repository/GymProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
Labels: new-feature

#85 chore(gym) : 함수 인자타입 변경
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
Labels: no-impact

#80 refactor(gym) : 제휴 헬스장 수정 리팩토링
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
Labels: minor-refactor, resolve-merge-conflict

#86 feat(machine) : machine 수정
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/dto/MachineRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/entity/Machine.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/mapper/MachineMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
Labels: new-feature

#89 chore(deploy): Write Deploy DockerCompose & DeployApplication Config
  .github/workflows/deploy.yml
  .gitignore
  docker/gymmate-deploy/docker-compose.deploy.template
  src/main/resources/application-deploy.template
Labels: docs-update, no-impact

#90 config(common): Fix application.md -> application.template
  .github/workflows/deploy.yml
  src/main/resources/docs/application-deploy.template
  src/main/resources/docs/application.template
Labels: docs-update, common-feature

#92 feat(gym) : gymTicket 등록
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/entity/GymTicket.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/enums/GymTicketStatus.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/mapper/GymTicketMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/repository/GymTicketRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/service/GymTicketService.java
  src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
Labels: new-feature

#96 refactor(gym): 대규모 - 파트너 헬스장 분리
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/RegisterGymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/request/UpdateGymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymImageResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymInfoResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymProductResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/PartnerGymDetailResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/repository/PartnerGymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/entity/GymProduct.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/mapper/GymProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/repository/GymProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
  src/main/java/org/helloworld/gymmate/domain/gym/machine/service/MachineService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/controller/PartnerGymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/entity/PartnerGym.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/mapper/PartnerGymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/repository/PartnerGymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/service/PartnerGymService.java
Labels: domain-refactor

#99 feat(gymProduct) : 헬스장 이용권 수정 및 삭제 구현
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/dto/GymProductRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/entity/GymProduct.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/mapper/GymProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/controller/PartnerGymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/dto/request/GymInfoRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/dto/request/GymRegisterRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/dto/request/GymUpdateRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/dto/request/RegisterGymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/dto/request/UpdateGymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnerGym/service/PartnerGymService.java
Labels: new-feature

#98 feat(gym) : 헬스장 정보 검색결과 목록 조회 구현
  src/main/java/org/helloworld/gymmate/domain/gym/enums/GymSearchOption.java
  src/main/java/org/helloworld/gymmate/domain/gym/enums/GymSortOption.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymDetailResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/dto/response/GymListResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymInfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
Labels: new-feature

#101 chore(deploy): Fix EC2 DocerCompose Error
  .github/workflows/deploy.yml
Labels: docs-update, no-impact

#104 feat(gym) : ticket 구매
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymProduct/service/GymProductService.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/controller/GymTicketController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/dto/GymTicketPurchaseResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/mapper/GymTicketMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymTicket/service/GymTicketService.java
  src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
Labels: new-feature

#109 chore(deploy): Modify Nginx Path
  docker/gymmate-deploy/docker-compose.deploy.template
  nginx/Dockerfile-nginx
Labels: docs-update, no-impact

#110 feat(gym): 헬스장 정보 단일 조회
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymDetailResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
Labels: new-feature

#108 feat(gym) : 헬스장 티켓 자동 만료 스케쥴러
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/entity/GymTicket.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketScheduler.java
Labels: new-feature

#111 feat(gym) : ticket 조회 (member)
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/MemberGymTicketResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/mapper/GymTicketMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
Labels: new-feature

#114 refactor(gymProduct) : 제휴 헬스장 이용권 수정
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/service/GymProductService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/dto/request/GymRegisterRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/dto/request/GymRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
Labels: minor-refactor

#116 feat(gym) : owner ticket 조회
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/PartnerGymTicketResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/mapper/GymTicketMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
Labels: new-feature

#118 refactor(gym) : 헬스장 정보 목록 & 검색 결과 조회 리팩토링
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
Labels: minor-refactor

#119 refactor(gym) : 더미데이터 삭제
  src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
Labels: minor-refactor

#113 feat(gym) : gym ticket 취소
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
Labels: new-feature

#120 feat(gym): 헬스장 소속 트레이너 목록 조회
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/TrainerDetailResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/repository/PtProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
Labels: new-feature

#123 refactor(gym) : 프론트 필요 항목
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/dto/MemberGymTicketResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/mapper/GymTicketMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/dao/PartnerGymNameProjection.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/repository/PartnerGymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
Labels: domain-refactor

#128 fix(common): Fix V1 INIT SCHEMA (with STUDENT) & Resolve Main Branch Error
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/controller/StudentController.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/dto/StudentsResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/entity/Student.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/mapper/StudentMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/repository/StudentRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
  src/main/resources/application-prod.yml
  src/main/resources/db/migration/V1__init_schema.sql
  src/main/resources/db/migration/V2__insert_initial_data.sql
  src/main/resources/docs/application-deploy.template
Labels: hotfix, common-feature

#126 refactor(trainer) : 트레이너 프로필사진 업데이트
  src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
Labels: minor-refactor

#129 feat(student) : 단일조회, 생성연결
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/controller/StudentController.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/dto/StudentDetailResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/mapper/StudentMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
Labels: new-feature

#131 refactor(gym) : 헬스장 단일 정보 조회시 이용권 정보 추가
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymDetailResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/mapper/GymProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/repository/PartnerGymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
Labels: minor-refactor

#132 config(common): Fix Deploy & Add Deploy Redis PW & SecurityConfig Refacoring
  .github/workflows/deploy.yml
  .gitignore
  build.gradle
  docker/gymmate-deploy/Dockerfile-deploy-backend
  src/main/java/org/helloworld/gymmate/common/config/RedisConfig.java
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/common/controller/HomeController.java
  src/main/resources/docs/application-deploy.template
  src/main/resources/docs/application.template
Labels: execution-ok, common-feature, dependency-update

#136 fix(security):Modify Cookie & Add Vercel Cors
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/common/cookie/CookieManager.java
  src/main/resources/docs/application-deploy.template
Labels: common-feature

#140 feat(gym) : 더미 이미지 등록 + id 못불러오는점 수정
  src/main/java/org/helloworld/gymmate/domain/gym/enums/GymDummyImage.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/infra/controller/CrawlerController.java
  src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
Labels: bugfix, new-feature

#143 docs(pt) : pt related controller swagger update
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClasstimeController.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/controller/ReservationController.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/controller/StudentController.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/dto/StudentsResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/mapper/StudentMapper.java
Labels: docs-update

#145 feat(ptProduct): 프론트 페이지 반영 컨트롤러 추가
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/dto/TrainersPtProductsResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/mapper/PtProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/service/PtProductService.java
Labels: new-feature

#146 docs(gym): Write Swagger MachineController
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
Labels: docs-update

#150 feat(award) : 등록 컨트롤러
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/controller/AwardController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/dto/AwardRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/mapper/AwardMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardService.java
Labels: new-feature

#152 feat(award) : award 삭제
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/controller/AwardController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardService.java
Labels: new-feature

#154 feat(dummy) : Trainer 및 제휴 헬스장 더미 데이터 생성
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymImageRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/enums/SocialProviderType.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
  src/main/java/org/helloworld/gymmate/dummy/controller/DummyDataController.java
  src/main/java/org/helloworld/gymmate/dummy/entity/GymDummyText.java
  src/main/java/org/helloworld/gymmate/dummy/entity/PartnerGymDummyImage.java
  src/main/java/org/helloworld/gymmate/dummy/entity/TrainerDummyImage.java
  src/main/java/org/helloworld/gymmate/dummy/entity/TrainerDummyText.java
  src/main/java/org/helloworld/gymmate/dummy/service/DummyDataService.java
Labels: new-feature

#153 feat(award) : 트레이너 본인 award 조회
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/controller/AwardController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/dto/AwardResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/mapper/AwardMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/service/AwardService.java
Labels: new-feature

#159 fix: 순환 참조 문제 해결
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
Labels: hotfix

#160 fix(myself): Improve Bigthree Scheduler & Bigthree Data Correction
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthreeaverage/scheduler/BigthreeAverageScheduler.java
  src/main/java/org/helloworld/gymmate/domain/user/member/repository/MemberRepository.java
  src/main/resources/db/migration/V5__insert_missing_bigthree.sql
  src/main/resources/db/migration/V6__reset_null_lifts_and_bigthree.sql
Labels: bugfix

#161 refactor(trainer) : 마이페이지 항목 빠진것 추가
  src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
Labels: minor-refactor

#163 fix(bigthree): Fix Flyway V6 <-> V5
  src/main/resources/db/migration/V5__reset_null_lifts_and_bigthree.sql
  src/main/resources/db/migration/V6__insert_missing_bigthree.sql
Labels: bugfix

#135 feat(gymreview) : 헬스장 리뷰 등록
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/controller/GymReviewController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/entity/GymReview.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/entity/GymReviewImage.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/mapper/GymReviewMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/repository/GymReviewImageRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/repository/GymReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/repository/GymTicketRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/service/GymTicketService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/entity/PartnerGym.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
  src/main/resources/db/migration/V7__add_gym_review.sql
Labels: new-feature

#165 fix(security): Add Cors EC2 Server
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
Labels: hotfix

#169 docs(gym): Write Swagger gymProduct
  src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/dto/GymProductRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/repository/GymProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymproduct/service/GymProductService.java
Labels: docs-update

#173 config(pay): Add Pay Key & Url
  .github/workflows/deploy.yml
  src/main/resources/docs/application.template
Labels: execution-ok, common-feature

#147 docs(gym): Write Swagger GymTicketController
  src/main/java/org/helloworld/gymmate/domain/gym/gymticket/controller/GymTicketController.java
Labels: docs-update

#176 docs(gym): Add Swagger Operation GymController
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
Labels: docs-update

#177 config(pay): Fix Application templete & Merge Pay
  src/main/java/org/helloworld/gymmate/common/config/RestClientConfig.java
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/payment/controller/PaymentController.java
  src/main/java/org/helloworld/gymmate/domain/payment/dto/request/PaymentRequest.java
  src/main/java/org/helloworld/gymmate/domain/payment/dto/response/PaymentResponse.java
  src/main/java/org/helloworld/gymmate/domain/payment/entity/Payment.java
  src/main/java/org/helloworld/gymmate/domain/payment/mapper/PaymentMapper.java
  src/main/java/org/helloworld/gymmate/domain/payment/properties/PaymentProperties.java
  src/main/java/org/helloworld/gymmate/domain/payment/repository/PaymentRepository.java
  src/main/java/org/helloworld/gymmate/domain/payment/service/PaymentService.java
  src/main/resources/db/migration/V8__add_payment.sql
  src/main/resources/docs/application.template
Labels: bugfix, execution-ok

#170 feat(payment) : 결제 기능 구현
  src/main/java/org/helloworld/gymmate/common/config/RestClientConfig.java
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/payment/controller/PaymentController.java
  src/main/java/org/helloworld/gymmate/domain/payment/dto/request/PaymentRequest.java
  src/main/java/org/helloworld/gymmate/domain/payment/dto/response/PaymentResponse.java
  src/main/java/org/helloworld/gymmate/domain/payment/entity/Payment.java
  src/main/java/org/helloworld/gymmate/domain/payment/mapper/PaymentMapper.java
  src/main/java/org/helloworld/gymmate/domain/payment/properties/PaymentProperties.java
  src/main/java/org/helloworld/gymmate/domain/payment/repository/PaymentRepository.java
  src/main/java/org/helloworld/gymmate/domain/payment/service/PaymentService.java
  src/main/resources/db/migration/V8__add_payment.sql
Labels: frontend-sync, new-feature

#178 refacotor(dummy): Add Trainer Dummy API & Refactoring
  src/main/java/org/helloworld/gymmate/dummy/controller/DummyDataController.java
  src/main/java/org/helloworld/gymmate/dummy/trainer/PtProductDummy.java
  src/main/java/org/helloworld/gymmate/dummy/trainer/PtProductImageDummy.java
  src/main/java/org/helloworld/gymmate/dummy/trainer/TrainerDummyCreate.java
  src/main/java/org/helloworld/gymmate/infra/controller/CrawlerController.java
Labels: hotfix

#179 fix(security) : @PreAuthroize 동작 되지 않던 문제 수정
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
Labels: bugfix

#168 feat(member) : 회원가입시 입력받은 주소 -> x y 변환
  src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
  src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
  src/main/java/org/helloworld/gymmate/infra/dto/Coordinate.java
  src/main/java/org/helloworld/gymmate/infra/dto/KakaoAddressResponse.java
  src/main/java/org/helloworld/gymmate/infra/service/KakaoMapRestTemplateComponent.java
  src/main/resources/db/migration/V8__update_member_nullXY.sql
Labels: new-feature

#172 feat(trainerReview) : 트레이너 리뷰 등록 구현
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/service/PtProductService.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/dto/ReservationRequest.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/repository/ReservationRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/entity/TrainerReview.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/entity/TrainerReviewImage.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewImageRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
  src/main/resources/db/migration/V10__add_trainer_review.sql
Labels: new-feature

#174 feat(gymreview) : 헬스장 리뷰 수정
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/controller/GymReviewController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/entity/GymReview.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
Labels: new-feature

#186 fix(dummy): 더미 생성기 헬스장 개수 변수로 변경
  src/main/java/org/helloworld/gymmate/dummy/service/DummyDataService.java
Labels: domain-refactor

#187 refactor(reservation) : PT 예약조회 리팩토링
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/controller/ReservationController.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/dto/ReservationTrainerResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/mapper/ReservationMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/repository/StudentRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
Labels: domain-refactor

#191 fix(security) : 시큐리티 설정변경
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
Labels: bugfix

#190 refactor(gym,trainer) : dto 변경 GymId 추가
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/dto/response/GymSearchResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerRegisterRequest.java
Labels: domain-refactor

#192 docs(gym): Add FlyWay Docs - Edit Null Facility
  src/main/resources/docs/VX__insert_facility_if_missing.templete
Labels: docs-update

#194 feat(trainerreview) : 트레이너 리뷰 수정 구현
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/entity/TrainerReview.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
Labels: new-feature

#195 feat(trainerreview) : 트레이너 리뷰 삭제
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/repository/ReservationRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/request/TrainerReviewModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerReviewDeleteEvent.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerReviewDeleteEventListener.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
Labels: new-feature

#193 docs(dummy): Add Query Docs Award & ClassTime & PtProduct
  src/main/resources/docs/insert_award_and_class_time_for_trainers.templete
  src/main/resources/docs/insert_facility_if_missing.templete
  src/main/resources/docs/insert_pt_products_for_trainers.templete
Labels: docs-update

#196 config(security), feat(trainerreview) : cors 에러 수정 & 트레이너 리뷰 조회
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/common/config/WebConfig.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/controller/TrainerReviewController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/response/TrainerReviewResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
Labels: new-feature

#197 fix(gym) : swagger error
  src/main/java/org/helloworld/gymmate/domain/gym/machine/controller/MachineController.java
Labels: bugfix

#198 feat(classtime) : 멤버의 트레이너 수업시간조회
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClasstimeController.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClasstimeService.java
Labels: new-feature

#175 feat(gymreview) : 헬스장 리뷰 삭제
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/controller/GymReviewController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymReviewDeleteEvent.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymReviewDeleteEventListener.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
Labels: new-feature

#199 feat(gym) : 제휴 헬스장 등록 주인 없는 헬스장만 조회되는 엔드포인트 추가
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/repository/PartnerGymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
Labels: hotfix, new-feature

#203 refacor(ptproduct) : pt상품명 수정 안되던점 수정
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/entity/PtProduct.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/service/PtProductService.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/repository/StudentRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/student/service/StudentService.java
Labels: hotfix, minor-refactor

#202 feat(gymreview): 헬스장 리뷰 조회 구현
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewImageResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/dto/GymReviewResponse.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/mapper/GymReviewMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/repository/GymReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/response/TrainerReviewResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
Labels: new-feature

#201 refactor(partnergym) : 파트너짐 등록시 trainer에 gym 업데이트 + 기존 owner 파트너짐 데이터 기반 업데이트 쿼리
  src/main/java/org/helloworld/gymmate/domain/gym/partnergym/service/PartnerGymService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
  src/main/resources/docs/update_trainer_gymid_by_partnergym.template
Labels: minor-refactor

#204 refactor(gym) : 전체 조회 검색 수정/GYMMATE-446
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/service/GymService.java
Labels: minor-refactor

#205 refactor(trainer_review) : refactor 트레이너 리뷰 리팩터링
  src/main/java/org/helloworld/gymmate/domain/user/enums/SocialProviderType.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/dto/response/TrainerReviewResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/mapper/TrainerReviewMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
Labels: minor-refactor

#206 refactor(reservation) : 돈 차감
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
Labels: minor-refactor

#208 refactor(review) : 정렬 DESC
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
Labels: minor-refactor

#209 refactor(reservation) : 예약시 회원 보유 금액과 PT 금액 비교 추가
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/service/ReservationService.java
Labels: minor-refactor

#211 feat(trainer) : 트레이너 리뷰 더미데이터 생성
  src/main/resources/docs/insert_trainer_review.template
Labels: new-feature

#212 fix(reservation) : 쿼리문 수정
  src/main/java/org/helloworld/gymmate/domain/pt/reservation/repository/ReservationRepository.java
Labels: bugfix

#213 refactor(trainer) : trainer score 리뷰 반영
  src/main/java/org/helloworld/gymmate/domain/gym/gyminfo/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymScoreEventListener.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/event/GymScoreUpdateEvent.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/repository/GymReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/gym/gymreview/service/GymReviewService.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/dto/TrainersPtProductsResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/ptproduct/mapper/PtProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/entity/Trainer.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerScoreEventListener.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/event/TrainerScoreUpdateEvent.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/repository/TrainerReviewRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/trainerreview/service/TrainerReviewService.java
Labels: minor-refactor
