Repository prgrms-web-devcourse-final-project/WEB3_4_HelloWorld_BE, pull requests merged in 2025-03, with the labels that each got.

#2 feat(trainer): 추가 정보 등록 구현
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/common/exception/GlobalExceptionHandler.java
  src/main/java/org/helloworld/gymmate/domain/user/GymMateTrainerController.java
  src/main/java/org/helloworld/gymmate/domain/user/dto/OwnerRegisterRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/dto/TrainerRegisterRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/enumerate/GenderType.java
  src/main/java/org/helloworld/gymmate/domain/user/enumerate/SocialProviderType.java
  src/main/java/org/helloworld/gymmate/domain/user/mapper/GymMateTrainerMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/mapper/SocialProviderMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/model/GymmateTrainer.java
  src/main/java/org/helloworld/gymmate/domain/user/model/SocialProvider.java
  src/main/java/org/helloworld/gymmate/domain/user/repository/GymMateTrainerRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/repository/SocialProviderRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/service/GymMateTrainerService.java
  src/main/java/org/helloworld/gymmate/security/authentication/GymMateTrainerDetails.java
Labels: new-feature

#3 feat(pt): PT 수업 가능 시간 추가
  src/main/java/org/helloworld/gymmate/common/exception/GlobalExceptionHandler.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClassTimeController.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/dto/ClassTimeRequest.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/entity/ClassTime.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/mapper/ClassTimeMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/repository/ClassTimeRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClassTimeService.java
Labels: new-feature

#5 feat(pt) : PT 수강 가능 시간 삭제
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/controller/ClassTimeController.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/repository/ClassTimeRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/service/ClassTimeService.java
Labels: new-feature

#9 docs(readme): Add Swagger&ERD Link /GYMMATE-205
  README.md
Labels: docs-update, no-impact

#12 refactor(common) : S3 파일매니저 리팩토링
  build.gradle
  src/main/java/org/helloworld/gymmate/common/config/S3Config.java
  src/main/java/org/helloworld/gymmate/common/properties/AwsS3Properties.java
  src/main/java/org/helloworld/gymmate/common/s3/FileManager.java
Labels: minor-refactor

#13 chore(classtime) : 전체조회 DTO 변경
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/dto/ClasstimesResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/classtime/mapper/ClasstimeMapper.java
Labels: execution-ok, no-impact

#14 config(common): Fix Application.md StaticRegion /GYMMATE-214
  src/main/resources/docs/application.md
Labels: hotfix, common-feature

#15 refactor(user): Move GymmateUser Files
  src/main/java/org/helloworld/gymmate/domain/user/member/service/GymmateUserDetailsService.java
  src/main/java/org/helloworld/gymmate/domain/user/model/GymmateUser.java
  src/main/java/org/helloworld/gymmate/domain/user/service/GymmateUserDetailsService.java
  src/main/java/org/helloworld/gymmate/domain/user/service/GymmateUserService.java
  src/main/java/org/helloworld/gymmate/security/authentication/AuthGymmateUserProvider.java
  src/main/java/org/helloworld/gymmate/security/authentication/GymmateUserDetails.java
  src/main/java/org/helloworld/gymmate/security/authentication/GymmateUserDetailsService.java
  src/main/java/org/helloworld/gymmate/security/oauth2/LoginSuccessHandler.java
Labels: domain-refactor

#16 feat(user) : user(member) 도메인 기본 세팅
  src/main/java/org/helloworld/gymmate/domain/user/member/controller/MemberController.java
  src/main/java/org/helloworld/gymmate/domain/user/member/dto/MemberRequest.java
  src/main/java/org/helloworld/gymmate/domain/user/member/entity/Member.java
  src/main/java/org/helloworld/gymmate/domain/user/member/repository/MemberRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/member/service/MemberService.java
Labels: new-feature

#17 feat(ptProduct) : ptProduct 생성 & 이미지 검증 추가
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/common/exception/GlobalExceptionHandler.java
  src/main/java/org/helloworld/gymmate/common/validate/custom/ImageFileValidator.java
  src/main/java/org/helloworld/gymmate/common/validate/custom/ValidImageFile.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/entity/PtProduct.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/entity/PtProductImage.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductImageRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
Labels: new-feature

#20 chore(classtime) : 에러코드 수정
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
Labels: minor-refactor

#23 feat(ptProduct) : ptProduct 삭제 및 연관 이미지 삭제
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
Labels: new-feature

#24 refactor(gym) : 제휴 헬스장 수정 이미지 부분 수정
  src/main/java/org/helloworld/gymmate/domain/gym/gym/controller/GymController.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/dto/GymUpdateRequest.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/service/GymService.java
Labels: new-feature

#26 feat(ptProduct): 전체조회 (필터,검색) 구현
  src/main/java/org/helloworld/gymmate/common/dto/PageDto.java
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/common/mapper/PageMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductsResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/SearchOption.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/enums/SortOption.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/repository/PtProductRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
Labels: new-feature

#29 feat(ptProduct) : 단일조회 구현
  src/main/java/org/helloworld/gymmate/domain/gym/gym/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/controller/PtProductController.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/dto/PtProductResponse.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/mapper/PtProductMapper.java
  src/main/java/org/helloworld/gymmate/domain/pt/pt_product/service/PtProductService.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/entity/Award.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/award/repository/AwardRepository.java
Labels: new-feature

#25 refactor(user): 소셜 로그인 리팩토링 /GYMMATE-217
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/common/rq/Rq.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/controller/TrainerController.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/dto/TrainerResponse.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/mapper/TrainerMapper.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/model/Trainer.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/repository/TrainerRepository.java
  src/main/java/org/helloworld/gymmate/domain/user/trainer/service/TrainerService.java
  src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
  src/main/java/org/helloworld/gymmate/security/model/GymMateTrainerDetails.java
  src/main/java/org/helloworld/gymmate/security/model/GymmateUser.java
  src/main/java/org/helloworld/gymmate/security/model/GymmateUserDetails.java
  src/main/java/org/helloworld/gymmate/security/oauth/entity/CustomOAuth2User.java
  src/main/java/org/helloworld/gymmate/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/org/helloworld/gymmate/security/resolver/CustomAuthorizationRequestResolver.java
  src/main/java/org/helloworld/gymmate/security/service/AuthGymmateUserProvider.java
  src/main/java/org/helloworld/gymmate/security/service/GymmateUserDetailsService.java
  src/main/java/org/helloworld/gymmate/security/service/GymmateUserService.java
  src/main/java/org/helloworld/gymmate/security/token/JwtManager.java
Labels: global-refactor

#30 feat(myself): Implement RecordController & CreateRecord
  src/main/java/org/helloworld/gymmate/domain/myself/record/controller/RecordController.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordModifyRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/dto/RecordResponse.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/entity/Record.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/repository/RecordRepository.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/service/RecordService.java
Labels: new-feature

#37 refactor(user): 추가 정보 페이지 URI 수정
  src/main/java/org/helloworld/gymmate/security/handler/LoginSuccessHandler.java
Labels: frontend-sync

#32 feat(myself): Implement ModifyRecord & GetRecords
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/controller/RecordController.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/mapper/RecordMapper.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/repository/RecordRepository.java
  src/main/java/org/helloworld/gymmate/domain/myself/record/service/RecordService.java
Labels: hotfix, new-feature

#39 feat(gym) : 헬스장 정보 크롤링
  build.gradle
  src/main/java/org/helloworld/gymmate/common/config/SecurityConfig.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/entity/Gym.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/mapper/GymMapper.java
  src/main/java/org/helloworld/gymmate/domain/gym/gym/repository/GymRepository.java
  src/main/java/org/helloworld/gymmate/infra/config/WebClientConfig.java
  src/main/java/org/helloworld/gymmate/infra/controller/CrawlerController.java
  src/main/java/org/helloworld/gymmate/infra/domain/gym/SeoulGymWebClientCrawler.java
  src/main/java/org/helloworld/gymmate/infra/service/KakaoMapWebClientService.java
  src/main/resources/docs/application.md
Labels: new-feature

#40 feat(myself): Implement CreateBigthree
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/dto/BigthreeCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/mapper/BigthreeMapper.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
Labels: new-feature

#38 feat(myself): Add Bigthree Package & Implement CreateBigthree
  src/main/java/org/helloworld/gymmate/common/exception/ErrorCode.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/dto/BigthreeCreateRequest.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/entity/Bigthree.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/mapper/BigthreeMapper.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/repository/BigthreeRepository.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
Labels: new-feature

#41 feat(myself): Implement DeleteBigthree
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/controller/BigthreeController.java
  src/main/java/org/helloworld/gymmate/domain/myself/bigthree/service/BigthreeService.java
Labels: new-feature
